<?php

/*
 +-----------------------------------------------------------------------+
 | localization/fr_FR/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube fetchmail_rc plugin                    |
 | Copyright (C) 2012, Iabsis                                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Gilles Hemmerlé <giloux@gmail.com>                            |
 +-----------------------------------------------------------------------+
 @version 1.0.0
*/

$labels = array();
$labels['accounts'] = 'Comptes POP/IMAP';
$labels['manageaccounts'] = 'Gestion des comptes à importer';